language: ruby
rvm:
- 2.1.3
env:
  global:
    secure: Sk39TX5v1vIa6nCSQfBlqJenvRXg0DeSXEBZaL/AIUqICOf5iukrrRsJXwpe64C3ceE6k9RKpkfWPb39jmyHre4sHbvj0O/ux34Xw852FWFK0Dp4hHRA7rCvCftmkNnDlr4dl9BgYPKpHpkUAB3RHqeCt111J6DO/MFgdD19FWk=
deploy:
  provider: rubygems
  gem: factor-connector-api
  api_key:
    secure: mMY5ZBtkbojnbXBLCnMpvdokLoJU+RbeafrQ3CZpOGXK4+mg8hoY79kdNIYNImF4bhOh3G0Ol0ByCsBGcciX1hknWLyrv8ZNNxlhoDLgTozcTIi8Zyd1SkRD360LUxGn5cDOgX+7o226zh6p2B742dVcgIf8Y469cGxT855DpBg=
  on:
    tags: true
    all_branches: true
