language: ruby
rvm:
- 1.9.3
env:
  global:
    secure: Sk39TX5v1vIa6nCSQfBlqJenvRXg0DeSXEBZaL/AIUqICOf5iukrrRsJXwpe64C3ceE6k9RKpkfWPb39jmyHre4sHbvj0O/ux34Xw852FWFK0Dp4hHRA7rCvCftmkNnDlr4dl9BgYPKpHpkUAB3RHqeCt111J6DO/MFgdD19FWk=
